DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NUMERO DE MATRICULA INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL;

-- para test --
INSERT INTO ODONTOLOGOS(NUMERO DE MATRICULA, NOMBRE, APELLIDO) VALUES (742, 'Valeria', 'Marciel');
INSERT INTO ODONTOLOGOS(NUMERO DE MATRICULA, NOMBRE, APELLIDO) VALUES (585, 'Daniel', 'Gutierrez');
INSERT INTO ODONTOLOGOS(NUMERO DE MATRICULA, NOMBRE, APELLIDO) VALUES (354, 'Blanca', 'Perez');